version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
      
# Github Actions updates
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 3
    rebase-strategy: disabled
